# Generated by Django 5.1.7 on 2025-03-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Subscription_Type',
            new_name='subscription_type',
        ),
    ]
